#!/usr/bin/env bash
# seed-anchor-key.sh — write the anchor-worker's ECDSA signer key into Vault.
#
# Why this exists: chain/init/init.sh seeds validator keys + the `deployer`
# signer key. vault-approle-bootstrap.sh creates the AppRole + policy that
# lets anchor-worker READ secret/haraledger/signer-keys/anchor-worker — but
# never creates the secret itself. Without this script the worker boots and
# immediately crashes with "Vault fetch failed: 404".
#
# Modes:
#   • Sim (no env set): uses anvil-1 (pre-funded in chain/qbft-config.json
#                       to 10000 HARA). Deterministic, re-runnable.
#   • Production:       you provide ANCHOR_ADDRESS + ANCHOR_PRIVATE_KEY env
#                       vars (generate with `cast wallet new`); the script
#                       writes them to Vault and reminds you to fund the
#                       address from the deployer.
#
# Required env (always):
#   VAULT_ADDR    default http://127.0.0.1:8200 if from the operator laptop,
#                 or http://vault:8200 if exec'd inside the hara-platform network
#   VAULT_TOKEN   dev root token (sim) OR root token from vault-init-keys.json (prod)

set -euo pipefail

VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"
: "${VAULT_TOKEN:?VAULT_TOKEN required}"

# Default to anvil-1 for the sim — pre-funded in genesis, deterministic.
# Production operators must override both env vars.
ANCHOR_ADDRESS="${ANCHOR_ADDRESS:-0x70997970C51812dc3A010C7d01b50e0d17dc79C8}"
ANCHOR_PRIVATE_KEY="${ANCHOR_PRIVATE_KEY:-0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d}"

log() { printf '\033[1;36m▶ %s\033[0m\n' "$*" >&2; }
ok()  { printf '\033[1;32m✓ %s\033[0m\n' "$*" >&2; }

# Validate the key looks like a 32-byte hex secret
echo "$ANCHOR_PRIVATE_KEY" | grep -qE '^0x[0-9a-fA-F]{64}$' || {
  echo "✗ ANCHOR_PRIVATE_KEY must be 0x + 64 hex chars" >&2
  exit 1
}

log "Writing anchor-worker key to Vault"
echo "  Vault: $VAULT_ADDR"
echo "  Path:  secret/haraledger/signer-keys/anchor-worker"
echo "  ECDSA address: $ANCHOR_ADDRESS"

# Use the KV v2 data endpoint. The anchor-worker reads "address" and
# "private_key" fields; PQ fields (pq_public_key, pq_secret_key) are
# generated by the worker on first run if absent.
curl -fsS \
  -H "X-Vault-Token: $VAULT_TOKEN" \
  -X POST \
  -d "{\"data\":{\"address\":\"$ANCHOR_ADDRESS\",\"private_key\":\"$ANCHOR_PRIVATE_KEY\"}}" \
  "$VAULT_ADDR/v1/secret/data/haraledger/signer-keys/anchor-worker" >/dev/null

ok "Seeded secret/haraledger/signer-keys/anchor-worker"

# Sanity check: read it back
log "Verifying read"
curl -fsS \
  -H "X-Vault-Token: $VAULT_TOKEN" \
  "$VAULT_ADDR/v1/secret/data/haraledger/signer-keys/anchor-worker" \
  | jq -e '.data.data.address and .data.data.private_key' >/dev/null \
  && ok "Read-back OK"

cat <<EOF

═════════════════════════════════════════════════════════════════════
  anchor-worker signer key seeded

  Address:     $ANCHOR_ADDRESS
  Vault path:  secret/haraledger/signer-keys/anchor-worker

EOF

if [ "$ANCHOR_ADDRESS" = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" ]; then
cat <<EOF
  ▶ Sim mode (anvil-1 default) — already pre-funded in genesis.
    Restart anchor-worker to pick up the key:
      docker restart hara-anchor-worker
EOF
else
cat <<EOF
  ▶ Production mode — fund this address from the deployer:
      cast send --legacy --gas-price 0 --value 1ether $ANCHOR_ADDRESS \\
        --rpc-url http://rpc.ledger.haratrust.io/write \\
        --private-key <deployer-private-key>
    Anchor-worker refuses to start with zero balance.
EOF
fi

cat <<EOF
═════════════════════════════════════════════════════════════════════
EOF
